# Generated by Django 4.2.6 on 2023-10-27 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_cad_usuarios", "0002_rename_usuarios_usuario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="usuario",
            new_name="Usuarios",
        ),
    ]
